name: RedstoneFlux
version: '${version}'
main: io.github.Jadiefication.redstoneflux.RedstoneFlux
author: Jadiefication
description: 'A library for energy system.'
api-version: '1.21'
folia-supported: true
load: STARTUP