name: EnergyLib
version: '${version}'
main: io.github.Jadiefication.redstoneflux.EnergyLib
author: Traqueur
description: 'A library for energy system.'
api-version: '1.21'
folia-supported: true
load: STARTUP